# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-image-release:
    name: Docker Image Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.title=WalletWatch Web Front-End
            org.opencontainers.image.description=WalletWatch front-end web app image, see https://github.com/walletwatch-id/web-backend for more info.
            org.opencontainers.image.vendor=WalletWatch
          annotations: |
            org.opencontainers.image.title=WalletWatch Web Front-End
            org.opencontainers.image.description=WalletWatch front-end web app image, see https://github.com/walletwatch-id/web-backend for more info.
            org.opencontainers.image.vendor=WalletWatch

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-cache:latest
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-cache:latest,mode=max
